config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :cat_breeds
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
# Description: Cat model
class Cat < ApplicationRecord
  belongs_to :cat_breed
  validates :name, presence: true, length: { in: 3..50 }, format: { with: /\A[a-zA-Z\s]+\z/ }
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cat_breed, presence: true
end

app/models/cat_breed.rb
# The CatBreed model is used to store the cat breed name.
class CatBreed < ApplicationRecord
  has_many :cats, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { in: 3..50 }, format: { with: /\A[^0-9][\w\s-]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_breeds_controller.rb
# The controller for the CatBreeds model
class CatBreedsController < ApplicationController
  before_action :set_cat_breed, only: %i[show edit update destroy]

  def index
    @cat_breeds = CatBreed.all
  end

  def show; end

  def new
    @cat_breed = CatBreed.new
  end

  def create
    @cat_breed = CatBreed.new(cat_breed_params)
    if @cat_breed.save
      redirect_to @cat_breed, notice: "Cat breed was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @cat_breed.update(cat_breed_params)
      redirect_to @cat_breed, notice: "Cat breed was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cat_breed.destroy
    redirect_to cat_breeds_url, notice: "Cat breed was successfully destroyed."
  end

  private

  def set_cat_breed
    @cat_breed = CatBreed.find(params[:id])
  end

  def cat_breed_params
    params.require(:cat_breed).permit(:name)
  end
end

app/controllers/cats_controller.rb
# The controller for the Cat model.
class CatsController < ApplicationController
  before_action :set_cat, only: %i[show edit update destroy]

  def index
    @cats = Cat.all
  end

  def show; end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to @cat, notice: "Cat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @cat.update(cat_params)
      redirect_to @cat, notice: "Cat was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cat.destroy
    redirect_to cats_url, notice: "Cat was successfully destroyed."
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :cat_breed_id, :age, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_breeds_helper.rb
# Helper for CatBreedsController
module CatBreedsHelper
end

app/helpers/cats_helper.rb
# Helper for cats
module CatsHelper
end

app/views/cats/index.html.erb
<h1 class="text-center my-3">All cats</h1>

<div class="container w-75">
  <div class="row">
    <% @cats.each do |cat| %>
      <div class="col-12 col-md-4 col-lg-3">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= cat.name %></h5>
            <p class="card-text"><%= cat.cat_breed.name %></p>
            <p class="card-text"><%= cat.age %> years old</p>
            <%= link_to "Show detail", cat_path(cat), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cats/show.html.erb
<h1 class="text-center my-3"><%= @cat.name %></h1>

<div class="container w-50 mx-auto">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @cat.name %></h5>
      <p class="card-text"><%= @cat.cat_breed.name %></p>
      <p class="card-text"><%= @cat.age %> years old</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAnimalsPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>